#!/usr/bin/env python3
"""Write first-run iDeer chatbot skill configuration from wizard JSON."""

from __future__ import annotations

import argparse
import json
import re
import shlex
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


DEFAULT_SOURCES = ["arxiv", "semanticscholar", "huggingface", "rss"]
ALLOWED_SOURCES = {"github", "huggingface", "twitter", "arxiv", "semanticscholar", "pubmed", "rss"}
DEFAULT_RSS_URLS = ["https://imjuya.github.io/juya-ai-daily/rss.xml"]
DEFAULT_TIMEZONE = "Asia/Shanghai"
DEFAULT_SCHEDULE_TIME = "13:00"
DEFAULT_FREQUENCY = "daily"
DEFAULT_DESCRIPTION = """I am working on artificial intelligence research.
Specifically, I am interested in:
1. Agent - LLM-based agents, tool use, multi-step reasoning, and agent evaluation
2. Safety - AI safety, alignment, hallucination, jailbreaks, and red-teaming
3. Applied AI - useful systems, research tooling, and model ecosystem updates

I'm not interested in unrelated entertainment or low-signal product announcements.

IMPORTANT: When generating the summary, please organize the content by each interest direction above.
"""


def repo_root_from_script() -> Path:
    return Path(__file__).resolve().parents[3]


def _read_json_stdin() -> dict[str, Any]:
    raw = sys.stdin.read().strip()
    if not raw:
        raise SystemExit("Expected setup JSON on stdin.")
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid setup JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise SystemExit("Setup JSON must be an object.")
    return data


def _string(value: Any, default: str = "") -> str:
    if value is None:
        return default
    return str(value).strip()


def _bool(value: Any, default: bool = False) -> bool:
    if value is None or value == "":
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def _int(value: Any, default: int) -> int:
    if value is None or value == "":
        return default
    return int(value)


def _list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        raw = re.split(r"[\s,|]+", value.strip())
    elif isinstance(value, list):
        raw = [str(item).strip() for item in value]
    else:
        raw = [str(value).strip()]
    return [item for item in raw if item]


def _normalize_sources(value: Any, x_api_key: str) -> tuple[list[str], list[str]]:
    warnings: list[str] = []
    candidates = _list(value) or DEFAULT_SOURCES
    sources: list[str] = []
    for source in candidates:
        normalized = source.lower()
        if normalized not in ALLOWED_SOURCES:
            warnings.append(f"Ignored unknown source: {source}")
            continue
        if normalized == "twitter" and not x_api_key:
            warnings.append("Ignored twitter source because X_RAPIDAPI_KEY is missing.")
            continue
        if normalized not in sources:
            sources.append(normalized)
    if not sources:
        sources = DEFAULT_SOURCES[:]
    return sources, warnings


def _normalize_time(value: str) -> str:
    value = value.strip() or DEFAULT_SCHEDULE_TIME
    if not re.match(r"^\d{1,2}:\d{2}$", value):
        raise SystemExit(f"Invalid schedule time: {value}. Expected HH:MM.")
    hour, minute = value.split(":", 1)
    hour_int = int(hour)
    minute_int = int(minute)
    if not (0 <= hour_int <= 23 and 0 <= minute_int <= 59):
        raise SystemExit(f"Invalid schedule time: {value}. Expected HH:MM.")
    return f"{hour_int:02d}:{minute_int:02d}"


def _normalize_frequency(value: str) -> str:
    value = (value or DEFAULT_FREQUENCY).strip().lower()
    if value not in {"daily", "weekdays", "weekly", "monthly"}:
        raise SystemExit(f"Invalid schedule frequency: {value}")
    return value


def _unquote_env(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def _parse_env(path: Path) -> tuple[list[str], dict[str, str], dict[str, int]]:
    if not path.exists():
        return ["# Auto-generated by ideer-daily-paper-chatbot first-run setup"], {}, {}
    lines = path.read_text(encoding="utf-8").splitlines()
    values: dict[str, str] = {}
    indexes: dict[str, int] = {}
    for idx, raw in enumerate(lines):
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key.startswith("export "):
            key = key[len("export ") :].strip()
        if not key:
            continue
        values[key] = _unquote_env(value)
        indexes[key] = idx
    return lines, values, indexes


def _quote_env(value: Any) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\n", "\\n")
    if text == "":
        return ""
    return shlex.quote(text)


def _merge_env(path: Path, desired: dict[str, Any], overwrite_existing: bool) -> dict[str, str]:
    lines, existing, indexes = _parse_env(path)
    final = dict(existing)
    added_heading = False
    for key, value in desired.items():
        value_text = "" if value is None else str(value)
        should_write = overwrite_existing or key not in existing or existing.get(key, "") == ""
        if should_write:
            rendered = f"{key}={_quote_env(value_text)}"
            if key in indexes:
                lines[indexes[key]] = rendered
            else:
                if not added_heading and path.exists():
                    lines.append("")
                    lines.append("# Added by ideer-daily-paper-chatbot first-run setup")
                    added_heading = True
                lines.append(rendered)
            final[key] = value_text
        else:
            final[key] = existing[key]
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return final


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}


def _write_text_if_needed(path: Path, text: str, overwrite_existing: bool, delete_if_empty: bool = False) -> bool:
    normalized = text.rstrip("\n")
    if not normalized and delete_if_empty:
        if path.exists() and overwrite_existing:
            path.unlink()
            return True
        return False
    if path.exists() and path.read_text(encoding="utf-8").strip() and not overwrite_existing:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(normalized + "\n", encoding="utf-8")
    return True


def _profile_text_from_urls(repo_root: Path, urls: list[str]) -> tuple[str, list[dict[str, Any]], list[str]]:
    if not urls:
        return "", [], []
    warnings: list[str] = []
    try:
        sys.path.insert(0, str(repo_root))
        from fetchers.profile_fetcher import build_profile_text_from_urls

        text, sources = build_profile_text_from_urls(urls)
        return text, sources, warnings
    except Exception as exc:
        warnings.append(f"Profile URL extraction failed: {exc}")
        fallback = "\n".join(f"Profile URL provided: {url}" for url in urls)
        return fallback, [{"url": url, "status": "unfetched"} for url in urls], warnings


def _build_ui_config(existing: dict[str, Any], env: dict[str, str], setup: dict[str, Any]) -> dict[str, Any]:
    sources = setup["sources"]
    schedule = setup["schedule"]
    smtp_port = _int(env.get("SMTP_PORT"), 465)
    config = {
        "desktop_python_path": existing.get("desktop_python_path", ""),
        "provider": env.get("PROVIDER", existing.get("provider", "openai")),
        "model": env.get("MODEL_NAME", existing.get("model", "gpt-4o-mini")),
        "base_url": env.get("BASE_URL", existing.get("base_url", "")),
        "api_key": env.get("API_KEY", existing.get("api_key", "")),
        "temperature": float(env.get("TEMPERATURE", existing.get("temperature", 0.5)) or 0.5),
        "smtp_server": env.get("SMTP_SERVER", existing.get("smtp_server", "")),
        "smtp_port": smtp_port,
        "sender": env.get("SMTP_SENDER", existing.get("sender", "")),
        "receiver": env.get("SMTP_RECEIVER", existing.get("receiver", "")),
        "smtp_password": env.get("SMTP_PASSWORD", existing.get("smtp_password", "")),
        "gh_languages": env.get("GH_LANGUAGES", existing.get("gh_languages", "all")),
        "gh_since": env.get("GH_SINCE", existing.get("gh_since", "daily")),
        "gh_max_repos": _int(env.get("GH_MAX_REPOS"), int(existing.get("gh_max_repos", 30) or 30)),
        "hf_content_types": _list(env.get("HF_CONTENT_TYPES")) or existing.get("hf_content_types", ["papers"]),
        "hf_max_papers": _int(env.get("HF_MAX_PAPERS"), int(existing.get("hf_max_papers", 30) or 30)),
        "hf_max_models": _int(env.get("HF_MAX_MODELS"), int(existing.get("hf_max_models", 15) or 15)),
        "description": setup["description"],
        "researcher_profile": setup["researcher_profile"],
        "x_rapidapi_key": env.get("X_RAPIDAPI_KEY", existing.get("x_rapidapi_key", "")),
        "x_rapidapi_host": env.get("X_RAPIDAPI_HOST", existing.get("x_rapidapi_host", "twitter-api45.p.rapidapi.com")),
        "x_accounts": existing.get("x_accounts", ""),
        "arxiv_categories": env.get("ARXIV_CATEGORIES", existing.get("arxiv_categories", "cs.AI cs.CL cs.LG")),
        "arxiv_max_entries": _int(env.get("ARXIV_MAX_ENTRIES"), int(existing.get("arxiv_max_entries", 100) or 100)),
        "arxiv_max_papers": _int(env.get("ARXIV_MAX_PAPERS"), int(existing.get("arxiv_max_papers", 60) or 60)),
        "ss_max_results": _int(env.get("SS_MAX_RESULTS"), int(existing.get("ss_max_results", 60) or 60)),
        "ss_max_papers": _int(env.get("SS_MAX_PAPERS"), int(existing.get("ss_max_papers", 30) or 30)),
        "ss_year": env.get("SS_YEAR", existing.get("ss_year", "")),
        "ss_api_key": env.get("SS_API_KEY", existing.get("ss_api_key", "")),
        "rss_urls": env.get("RSS_URLS", existing.get("rss_urls", " ".join(DEFAULT_RSS_URLS))),
        "rss_max_items": _int(env.get("RSS_MAX_ITEMS"), int(existing.get("rss_max_items", 30) or 30)),
        "schedule_enabled": False,
        "schedule_frequency": schedule["frequency"],
        "schedule_time": schedule["time"],
        "schedule_sources": sources,
        "schedule_generate_report": True,
        "schedule_generate_ideas": setup["generate_ideas"],
    }
    return config


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=repo_root_from_script())
    parser.add_argument("--overwrite-existing", action="store_true", help="Overwrite existing non-empty config values")
    parser.add_argument("--no-ui-config", action="store_true", help="Do not write .web_config.json/.client_config.json")
    parser.add_argument("--no-state", action="store_true", help="Do not write state/ideer_chatbot_setup.json")
    args = parser.parse_args()

    repo_root = args.repo_root.expanduser().resolve()
    data = _read_json_stdin()

    env_file = repo_root / ".env"
    _, existing_env, _ = _parse_env(env_file)

    smtp = data.get("smtp") if isinstance(data.get("smtp"), dict) else {}
    receiver = (
        _string(data.get("receiver"))
        or _string(data.get("email"))
        or _string(smtp.get("receiver"))
        or existing_env.get("SMTP_RECEIVER", "").strip()
    )
    if not receiver:
        raise SystemExit("receiver is required for first-run setup.")

    description = _string(data.get("description")) or _string(data.get("research_direction")) or DEFAULT_DESCRIPTION
    scholar_urls = _list(data.get("scholar_urls") or data.get("scholar_url") or data.get("profile_urls"))
    profile_url_text, profile_sources, profile_warnings = _profile_text_from_urls(repo_root, scholar_urls)
    researcher_profile = _string(data.get("researcher_profile"))
    if profile_url_text:
        parts = [part for part in [researcher_profile, "[Profile URL context]\n" + profile_url_text] if part.strip()]
        researcher_profile = "\n\n".join(parts)

    x_api_key = _string(data.get("x_rapidapi_key")) or existing_env.get("X_RAPIDAPI_KEY", "")
    sources, source_warnings = _normalize_sources(data.get("sources"), x_api_key)

    schedule_input = data.get("schedule") if isinstance(data.get("schedule"), dict) else {}
    schedule = {
        "enabled": False,
        "frequency": _normalize_frequency(_string(schedule_input.get("frequency") or data.get("schedule_frequency"), DEFAULT_FREQUENCY)),
        "time": _normalize_time(_string(schedule_input.get("time") or data.get("schedule_time"), DEFAULT_SCHEDULE_TIME)),
        "timezone": _string(schedule_input.get("timezone") or data.get("timezone"), DEFAULT_TIMEZONE),
    }

    smtp_server = _string(data.get("smtp_server")) or _string(smtp.get("server"))
    smtp_sender = _string(data.get("sender")) or _string(smtp.get("sender"))
    smtp_password = _string(data.get("smtp_password")) or _string(smtp.get("password"))
    smtp_port = _string(data.get("smtp_port")) or _string(smtp.get("port")) or "465"
    generate_ideas = _bool(data.get("generate_ideas"), False)

    profile_file = repo_root / "profiles" / "description.txt"
    researcher_profile_file = repo_root / "profiles" / "researcher_profile.md"
    _write_text_if_needed(profile_file, description, args.overwrite_existing)
    wrote_researcher = False
    if researcher_profile.strip():
        wrote_researcher = _write_text_if_needed(
            researcher_profile_file,
            researcher_profile,
            args.overwrite_existing,
            delete_if_empty=False,
        )
    effective_description = profile_file.read_text(encoding="utf-8").strip() if profile_file.exists() else description
    effective_researcher_profile = (
        researcher_profile_file.read_text(encoding="utf-8").strip()
        if researcher_profile_file.exists()
        else researcher_profile
    )

    desired_env: dict[str, Any] = {
        "PROVIDER": "openai",
        "MODEL_NAME": "gpt-4o-mini",
        "BASE_URL": "",
        "API_KEY": "",
        "TEMPERATURE": "0.5",
        "SMTP_SERVER": smtp_server,
        "SMTP_PORT": smtp_port,
        "SMTP_SENDER": smtp_sender,
        "SMTP_RECEIVER": receiver,
        "SMTP_PASSWORD": smtp_password,
        "DESCRIPTION_FILE": "profiles/description.txt",
        "DAILY_SOURCES": " ".join(sources),
        "NUM_WORKERS": "6",
        "GENERATE_REPORT": "1",
        "SEND_REPORT_EMAIL": "0",
        "SKIP_SOURCE_EMAILS": "1",
        "REPORT_TITLE": "Daily Personal Briefing",
        "REPORT_MIN_SCORE": "4.0",
        "REPORT_MAX_ITEMS": "18",
        "REPORT_THEME_COUNT": "4",
        "REPORT_PREDICTION_COUNT": "4",
        "REPORT_IDEA_COUNT": "4",
        "GENERATE_IDEAS": "1" if generate_ideas else "0",
        "IDEA_MIN_SCORE": "7",
        "IDEA_MAX_ITEMS": "15",
        "IDEA_COUNT": "5",
        "ARXIV_CATEGORIES": "cs.AI cs.CL cs.LG",
        "ARXIV_MAX_ENTRIES": "100",
        "ARXIV_MAX_PAPERS": "60",
        "SS_QUERIES": "",
        "SS_MAX_RESULTS": "60",
        "SS_MAX_PAPERS": "30",
        "SS_YEAR": "",
        "SS_FIELDS_OF_STUDY": "Computer Science",
        "SS_API_KEY": "",
        "GH_LANGUAGES": "all",
        "GH_SINCE": "daily",
        "GH_MAX_REPOS": "30",
        "HF_CONTENT_TYPES": "papers",
        "HF_MAX_PAPERS": "30",
        "HF_MAX_MODELS": "15",
        "RSS_URLS": " ".join(DEFAULT_RSS_URLS),
        "RSS_MAX_ITEMS": "30",
        "X_RAPIDAPI_KEY": x_api_key,
        "X_RAPIDAPI_HOST": "twitter-api45.p.rapidapi.com",
        "X_ACCOUNTS_FILE": "profiles/x_accounts.txt",
        "X_DISCOVER_ACCOUNTS": "0",
        "X_MERGE_STATIC_ACCOUNTS": "0",
        "X_USE_PERSISTED_ACCOUNTS": "0",
        "X_SKIP_DISCOVERY_IF_PERSISTED": "1",
        "X_DISCOVERY_PERSIST_FILE": "state/x_accounts.discovered.txt",
    }
    if effective_researcher_profile.strip() or wrote_researcher:
        desired_env["REPORT_PROFILE_FILE"] = "profiles/researcher_profile.md"
        desired_env["RESEARCHER_PROFILE"] = "profiles/researcher_profile.md"

    repo_root.mkdir(parents=True, exist_ok=True)
    final_env = _merge_env(env_file, desired_env, args.overwrite_existing)

    warnings = source_warnings + profile_warnings
    smtp_configured = bool(final_env.get("SMTP_SERVER") and final_env.get("SMTP_SENDER") and final_env.get("SMTP_PASSWORD"))
    setup_summary = {
        "version": 1,
        "configured_at": datetime.now(timezone.utc).isoformat(),
        "receiver": final_env.get("SMTP_RECEIVER", receiver),
        "sources": sources,
        "rss_urls": _list(final_env.get("RSS_URLS")) or DEFAULT_RSS_URLS,
        "schedule": schedule,
        "send_email": False,
        "smtp_configured": smtp_configured,
        "generate_report": True,
        "generate_ideas": generate_ideas,
        "description_file": "profiles/description.txt",
        "researcher_profile_file": "profiles/researcher_profile.md" if effective_researcher_profile.strip() else "",
        "profile_urls": scholar_urls,
        "profile_url_results": profile_sources,
        "warnings": warnings,
    }

    if not args.no_state:
        state_path = repo_root / "state" / "ideer_chatbot_setup.json"
        state_path.parent.mkdir(parents=True, exist_ok=True)
        state_path.write_text(json.dumps(setup_summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    if not args.no_ui_config:
        existing_ui = _read_json(repo_root / ".web_config.json")
        ui_config = _build_ui_config(existing_ui, final_env, {
            "sources": sources,
            "schedule": schedule,
            "description": effective_description,
            "researcher_profile": effective_researcher_profile,
            "generate_ideas": generate_ideas,
        })
        for path in (repo_root / ".web_config.json", repo_root / ".client_config.json"):
            path.write_text(json.dumps(ui_config, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(json.dumps({
        "status": "ok",
        "env_file": str(env_file),
        "description_file": str(profile_file),
        "researcher_profile_file": str(researcher_profile_file) if effective_researcher_profile.strip() else "",
        "sources": sources,
        "schedule": schedule,
        "send_email": False,
        "smtp_configured": smtp_configured,
        "warnings": warnings,
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
